(() => {
  if (window.__mochiLensLoaded) {
    return;
  }

  window.__mochiLensLoaded = true;

  const BRIDGE_REQUEST_SOURCE = "MOCHILENS_CONTENT";
  const BRIDGE_RESPONSE_SOURCE = "MOCHILENS_PAGE";
  const FALLBACK_INNERTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
  const INNERTUBE_CLIENTS = [
    {
      name: "ANDROID_VR",
      version: "1.61.48",
      id: "28",
      extra: {
        androidSdkVersion: 32,
        deviceMake: "Oculus",
        deviceModel: "Quest 3",
        osName: "Android",
        osVersion: "12L"
      }
    },
    {
      name: "IOS",
      version: "20.10.4",
      id: "5",
      extra: {
        deviceMake: "Apple",
        deviceModel: "iPhone16,2",
        osName: "iPhone",
        osVersion: "18.3.2.22D82"
      }
    },
    {
      name: "TVHTML5_SIMPLY_EMBEDDED_PLAYER",
      version: "2.0",
      id: "85",
      extra: {}
    },
    {
      name: "MWEB",
      version: "2.20250606.01.00",
      id: "2",
      extra: {}
    }
  ];

  function injectPageBridge() {
    return new Promise((resolve, reject) => {
      const existingBridge = document.querySelector("#mochilens-page-bridge");

      if (existingBridge?.dataset.loaded === "true") {
        resolve();
        return;
      }

      const script = existingBridge || document.createElement("script");
      script.id = "mochilens-page-bridge";
      script.src = chrome.runtime.getURL("page-bridge.js");

      script.addEventListener(
        "load",
        () => {
          script.dataset.loaded = "true";
          resolve();
        },
        { once: true }
      );
      script.addEventListener("error", () => reject(new Error("播放器桥接加载失败。")), {
        once: true
      });

      if (!existingBridge) {
        document.documentElement.appendChild(script);
      }
    });
  }

  const pageBridgeReady = injectPageBridge();

  function getVideoTitle() {
    const titleElement = document.querySelector(
      [
        "ytd-watch-metadata h1 yt-formatted-string",
        "h1.title yt-formatted-string",
        "ytd-reel-video-renderer[is-active] h2 yt-formatted-string",
        "ytd-reel-video-renderer[is-active] #title"
      ].join(", ")
    );
    const socialTitle = document.querySelector('meta[property="og:title"]')?.content;
    const documentTitle = document.title.replace(/\s*-\s*YouTube\s*$/, "").trim();

    return titleElement?.textContent.trim() || socialTitle?.trim() || documentTitle;
  }

  function getVideoId(url) {
    if (url.pathname === "/watch") {
      return url.searchParams.get("v");
    }

    const pathMatch = url.pathname.match(/^\/(?:shorts|live|embed)\/([^/?#]+)/);
    return pathMatch?.[1] || null;
  }

  function getVideoInfo() {
    const url = new URL(window.location.href);
    const videoId = getVideoId(url);

    if (!videoId) {
      return { isYouTubeVideo: false };
    }

    return {
      isYouTubeVideo: true,
      url: url.href,
      videoId,
      title: getVideoTitle() || "未获取到标题"
    };
  }

  async function requestCaptionTracks(videoId) {
    await pageBridgeReady;

    return new Promise((resolve, reject) => {
      const requestId = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
      const timeoutId = window.setTimeout(() => {
        window.removeEventListener("message", handleBridgeResponse);
        reject(new Error("读取播放器字幕信息超时。"));
      }, 12000);

      function handleBridgeResponse(event) {
        const data = event.data;

        if (
          event.source !== window ||
          event.origin !== window.location.origin ||
          data?.source !== BRIDGE_RESPONSE_SOURCE ||
          data?.type !== "PLAYER_DATA" ||
          data?.requestId !== requestId
        ) {
          return;
        }

        window.clearTimeout(timeoutId);
        window.removeEventListener("message", handleBridgeResponse);

        if (data.error) {
          reject(new Error(data.error));
          return;
        }

        resolve(data);
      }

      window.addEventListener("message", handleBridgeResponse);
      window.postMessage(
        {
          source: BRIDGE_REQUEST_SOURCE,
          type: "GET_PLAYER_DATA",
          requestId,
          videoId
        },
        window.location.origin
      );
    });
  }

  function getTrackName(name) {
    if (name?.simpleText) {
      return name.simpleText;
    }

    return (name?.runs || []).map((run) => run.text || "").join("").trim();
  }

  function normalizeCaptionTracks(tracks) {
    return (tracks || []).map((track) => ({
      baseUrl: track.baseUrl,
      languageCode: track.languageCode || "",
      languageName: getTrackName(track.name) || track.languageCode || "未知语言",
      isAutoGenerated: track.kind === "asr",
      sourceClient: track.sourceClient || null
    }));
  }

  function addDiagnostic(diagnostics, stage, details = {}) {
    diagnostics.steps.push({ stage, ...details });
  }

  function summarizeTrackUrl(baseUrl) {
    try {
      const url = new URL(baseUrl);
      return {
        host: url.host,
        path: url.pathname,
        queryKeys: Array.from(new Set(url.searchParams.keys())).sort()
      };
    } catch {
      return { invalidUrl: true };
    }
  }

  function extractAssignedJson(source, variableName) {
    const assignmentPattern = new RegExp(`${variableName}\\s*=\\s*`, "g");
    let assignment;

    while ((assignment = assignmentPattern.exec(source))) {
      const start = source.indexOf("{", assignmentPattern.lastIndex);

      if (start === -1) {
        continue;
      }

      let depth = 0;
      let inString = false;
      let escaped = false;

      for (let index = start; index < source.length; index += 1) {
        const character = source[index];

        if (inString) {
          if (escaped) {
            escaped = false;
          } else if (character === "\\") {
            escaped = true;
          } else if (character === '"') {
            inString = false;
          }
          continue;
        }

        if (character === '"') {
          inString = true;
        } else if (character === "{") {
          depth += 1;
        } else if (character === "}") {
          depth -= 1;

          if (depth === 0) {
            try {
              return JSON.parse(source.slice(start, index + 1));
            } catch {
              break;
            }
          }
        }
      }
    }

    return null;
  }

  function extractPageConfigString(pageHtml, key) {
    const pattern = new RegExp(`"${key}"\\s*:\\s*"([^"\\\\]+)"`);
    return pageHtml.match(pattern)?.[1] || null;
  }

  function isPoProtectedTrack(track) {
    try {
      return new URL(track.baseUrl).searchParams.get("exp") === "xpe";
    } catch {
      return false;
    }
  }

  async function requestCaptionTracksFromPage(videoId, diagnostics) {
    const watchUrl = new URL("/watch", window.location.origin);
    watchUrl.searchParams.set("v", videoId);
    const pageResponse = await fetch(watchUrl.href, { credentials: "include" });

    addDiagnostic(diagnostics, "watch-page-response", {
      status: pageResponse.status,
      ok: pageResponse.ok
    });

    if (!pageResponse.ok) {
      throw new Error(`视频页面读取失败（HTTP ${pageResponse.status}）。`);
    }

    const pageHtml = await pageResponse.text();
    const playerResponse = extractAssignedJson(pageHtml, "ytInitialPlayerResponse");

    addDiagnostic(diagnostics, "watch-page-parse", {
      bodyLength: pageHtml.length,
      playerResponseFound: Boolean(playerResponse),
      responseVideoIdMatches: playerResponse?.videoDetails?.videoId === videoId
    });

    if (!playerResponse || playerResponse.videoDetails?.videoId !== videoId) {
      throw new Error("未找到当前视频的页面字幕数据。");
    }

    const tracks = playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks;

    addDiagnostic(diagnostics, "watch-page-tracks", {
      trackCount: tracks?.length || 0
    });

    return {
      videoId,
      captionTracks: normalizeCaptionTracks(tracks),
      apiKey:
        extractPageConfigString(pageHtml, "INNERTUBE_API_KEY") ||
        FALLBACK_INNERTUBE_API_KEY
    };
  }

  async function requestCaptionTracksFromInnertube(videoId, apiKey, diagnostics) {
    const endpoint = new URL("/youtubei/v1/player", window.location.origin);
    endpoint.searchParams.set("prettyPrint", "false");
    endpoint.searchParams.set("key", apiKey || FALLBACK_INNERTUBE_API_KEY);
    let protectedResult = null;

    for (const client of INNERTUBE_CLIENTS) {
      let response;

      try {
        response = await fetch(endpoint.href, {
          method: "POST",
          credentials: "omit",
          headers: {
            "Content-Type": "application/json",
            "X-YouTube-Client-Name": client.id,
            "X-YouTube-Client-Version": client.version
          },
          body: JSON.stringify({
            context: {
              client: {
                clientName: client.name,
                clientVersion: client.version,
                hl: "en",
                gl: "US",
                ...client.extra
              }
            },
            videoId,
            contentCheckOk: true,
            racyCheckOk: true
          })
        });
      } catch (error) {
        addDiagnostic(diagnostics, "innertube-player", {
          client: client.name,
          networkError: error.message
        });
        continue;
      }

      let playerResponse;

      try {
        playerResponse = await response.json();
      } catch {
        addDiagnostic(diagnostics, "innertube-player", {
          client: client.name,
          status: response.status,
          ok: response.ok,
          responseParsed: false
        });
        continue;
      }

      const rawTracks =
        playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
      const tracks = normalizeCaptionTracks(
        rawTracks.map((track) => ({ ...track, sourceClient: client.name }))
      );
      const unprotectedTracks = tracks.filter((track) => !isPoProtectedTrack(track));

      addDiagnostic(diagnostics, "innertube-player", {
        client: client.name,
        status: response.status,
        ok: response.ok,
        playabilityStatus: playerResponse.playabilityStatus?.status || null,
        responseVideoIdMatches: playerResponse.videoDetails?.videoId === videoId,
        trackCount: tracks.length,
        unprotectedTrackCount: unprotectedTracks.length
      });

      if (playerResponse.videoDetails?.videoId !== videoId || !tracks.length) {
        continue;
      }

      if (unprotectedTracks.length) {
        return {
          videoId,
          captionTracks: unprotectedTracks,
          runtimeCaptionUrls: [],
          captionSource: "innertube",
          sourceClient: client.name
        };
      }

      protectedResult ||= {
        videoId,
        captionTracks: tracks,
        runtimeCaptionUrls: [],
        captionSource: "innertube-protected",
        sourceClient: client.name
      };
    }

    return protectedResult;
  }

  async function findCaptionTracks(videoId, diagnostics) {
    let bridgeError;
    let bridgeData;

    try {
      bridgeData = await requestCaptionTracks(videoId);

      addDiagnostic(diagnostics, "player-bridge", {
        responseVideoId: bridgeData.videoId || null,
        videoIdMatches: bridgeData.videoId === videoId,
        trackCount: bridgeData.captionTracks?.length || 0,
        runtimeCaptionUrlCount: bridgeData.runtimeCaptionUrls?.length || 0,
        captionsActivated: Boolean(bridgeData.captionsActivated),
        captionTriggerAttempts: bridgeData.captionTriggerAttempts || 0,
        runtimeUrls: (bridgeData.runtimeCaptionUrls || []).map(summarizeTrackUrl)
      });

      if (
        bridgeData.videoId === videoId &&
        bridgeData.captionTracks?.length &&
        bridgeData.runtimeCaptionUrls?.length
      ) {
        return bridgeData;
      }
    } catch (error) {
      bridgeError = error;
      addDiagnostic(diagnostics, "player-bridge-error", { error: error.message });
    }

    try {
      const pageData = await requestCaptionTracksFromPage(videoId, diagnostics);
      pageData.runtimeCaptionUrls = bridgeData?.runtimeCaptionUrls || [];

      if (pageData.runtimeCaptionUrls.length) {
        return pageData;
      }

      const innertubeData = await requestCaptionTracksFromInnertube(
        videoId,
        pageData.apiKey,
        diagnostics
      );

      if (innertubeData?.captionTracks?.length) {
        return innertubeData;
      }

      return pageData;
    } catch (pageError) {
      addDiagnostic(diagnostics, "watch-page-error", { error: pageError.message });
      throw bridgeError || pageError;
    }
  }

  function selectCaptionTrack(tracks, runtimeUrls, videoId) {
    const selected = tracks.find((track) => !track.isAutoGenerated) || tracks[0] || null;

    if (!selected) {
      return null;
    }

    const runtimeUrl = (runtimeUrls || []).find((urlText) => {
      try {
        const url = new URL(urlText);
        const languageMatches = !selected.languageCode || url.searchParams.get("lang") === selected.languageCode;
        const kindMatches = selected.isAutoGenerated
          ? url.searchParams.get("kind") === "asr"
          : url.searchParams.get("kind") !== "asr";
        return url.searchParams.get("v") === videoId && languageMatches && kindMatches;
      } catch {
        return false;
      }
    });

    return { ...selected, runtimeUrl: runtimeUrl || runtimeUrls?.[0] || null };
  }

  function parseJson3Transcript(payload) {
    const segments = (payload.events || [])
      .map((event) => ({
        startMs: event.tStartMs || 0,
        durationMs: event.dDurationMs || 0,
        text: (event.segs || []).map((segment) => segment.utf8 || "").join("")
      }))
      .filter((segment) => segment.text.trim())
      .map((segment) => ({
        ...segment,
        text: segment.text.replace(/\s+/g, " ").trim()
      }));

    return {
      transcript: segments.map((segment) => segment.text).join(" ").trim(),
      segmentCount: segments.length
    };
  }

  function parseXmlTranscript(body) {
    const documentNode = new DOMParser().parseFromString(body, "text/xml");

    if (documentNode.querySelector("parsererror")) {
      return { transcript: "", segmentCount: 0 };
    }

    const paragraphNodes = Array.from(documentNode.querySelectorAll("p"));
    const captionNodes = paragraphNodes.length
      ? paragraphNodes
      : Array.from(documentNode.querySelectorAll("text"));
    const segments = captionNodes
      .map((node) => node.textContent.replace(/\s+/g, " ").trim())
      .filter(Boolean);

    return {
      transcript: segments.join(" ").trim(),
      segmentCount: segments.length
    };
  }

  function parseTranscriptBody(body) {
    try {
      const parsed = parseJson3Transcript(JSON.parse(body));

      if (parsed.transcript) {
        return parsed;
      }
    } catch {
      // The original caption URL may return XML instead of JSON.
    }

    return parseXmlTranscript(body);
  }

  function setCaptionFormatWithoutResigning(baseUrl, format) {
    if (/([?&])fmt=[^&]*/.test(baseUrl)) {
      return baseUrl.replace(/([?&])fmt=[^&]*/, `$1fmt=${format}`);
    }

    return `${baseUrl}${baseUrl.includes("?") ? "&" : "?"}fmt=${format}`;
  }

  async function downloadTranscript(track, diagnostics) {
    const json3Url = setCaptionFormatWithoutResigning(track.baseUrl, "json3");
    const runtimeJson3Url = track.runtimeUrl
      ? setCaptionFormatWithoutResigning(track.runtimeUrl, "json3")
      : null;
    const attempts = [
      track.runtimeUrl && { url: track.runtimeUrl, credentials: "include", kind: "runtime" },
      runtimeJson3Url && { url: runtimeJson3Url, credentials: "include", kind: "runtime-json3" },
      { url: json3Url, credentials: "include", kind: "base-json3" },
      { url: track.baseUrl, credentials: "include", kind: "base-original" },
      { url: track.baseUrl, credentials: "omit", kind: "base-original" }
    ]
      .filter(Boolean)
      .filter(
        (attempt, index, allAttempts) =>
          allAttempts.findIndex(
            (candidate) =>
              candidate.url === attempt.url && candidate.credentials === attempt.credentials
          ) === index
      );
    let lastStatus = null;
    let receivedBody = false;

    addDiagnostic(diagnostics, "selected-track", {
      languageCode: track.languageCode,
      languageName: track.languageName,
      isAutoGenerated: track.isAutoGenerated,
      sourceClient: track.sourceClient,
      poProtected: isPoProtectedTrack(track),
      url: summarizeTrackUrl(track.baseUrl),
      runtimeUrl: track.runtimeUrl ? summarizeTrackUrl(track.runtimeUrl) : null
    });

    for (const [index, attempt] of attempts.entries()) {
      let response;

      try {
        response = await fetch(attempt.url, { credentials: attempt.credentials });
      } catch (error) {
        addDiagnostic(diagnostics, "caption-request", {
          attempt: index + 1,
          requestKind: attempt.kind,
          credentials: attempt.credentials,
          networkError: error.message
        });
        continue;
      }

      lastStatus = response.status;

      if (!response.ok) {
        addDiagnostic(diagnostics, "caption-request", {
          attempt: index + 1,
          requestKind: attempt.kind,
          credentials: attempt.credentials,
          status: response.status,
          ok: false,
          bodyLength: null,
          contentType: response.headers?.get?.("content-type") || null
        });
        continue;
      }

      const body = await response.text();

      addDiagnostic(diagnostics, "caption-request", {
        attempt: index + 1,
        requestKind: attempt.kind,
        credentials: attempt.credentials,
        status: response.status,
        ok: true,
        bodyLength: body.length,
        contentType: response.headers?.get?.("content-type") || null
      });

      if (!body.trim()) {
        continue;
      }

      receivedBody = true;
      const parsed = parseTranscriptBody(body);

      addDiagnostic(diagnostics, "caption-parse", {
        attempt: index + 1,
        segmentCount: parsed.segmentCount,
        transcriptLength: parsed.transcript.length
      });

      if (parsed.transcript) {
        return parsed;
      }
    }

    if (!receivedBody) {
      throw new Error(
        lastStatus && lastStatus !== 200
          ? `字幕下载失败（HTTP ${lastStatus}）。`
          : "字幕轨道返回了空内容。"
      );
    }

    throw new Error("字幕格式无法解析或内容为空。");
  }

  async function getTranscript(expectedVideoId, diagnostics) {
    const currentVideo = getVideoInfo();

    if (!currentVideo.isYouTubeVideo || currentVideo.videoId !== expectedVideoId) {
      throw new Error("视频已切换，请重新打开插件后再试。");
    }

    const playerData = await findCaptionTracks(expectedVideoId, diagnostics);

    if (playerData.videoId !== expectedVideoId) {
      throw new Error("播放器仍在切换视频，请稍后重试。");
    }

    const track = selectCaptionTrack(
      playerData.captionTracks || [],
      playerData.runtimeCaptionUrls || [],
      expectedVideoId
    );

    addDiagnostic(diagnostics, "track-selection", {
      availableTrackCount: playerData.captionTracks?.length || 0,
      selected: Boolean(track)
    });

    if (!track) {
      throw new Error("该视频没有可用字幕。");
    }

    const parsed = await downloadTranscript(track, diagnostics);

    return {
      ok: true,
      videoId: expectedVideoId,
      transcript: parsed.transcript,
      segmentCount: parsed.segmentCount,
      languageCode: track.languageCode,
      languageName: track.languageName,
      isAutoGenerated: track.isAutoGenerated
    };
  }

  let audioCapturePlaybackState = null;

  function getVisibleVideoElement() {
    const viewportWidth = window.innerWidth;
    const viewportHeight = window.innerHeight;

    return [...document.querySelectorAll("video")]
      .map((video) => {
        const rect = video.getBoundingClientRect();
        const visibleWidth = Math.max(
          0,
          Math.min(rect.right, viewportWidth) - Math.max(rect.left, 0)
        );
        const visibleHeight = Math.max(
          0,
          Math.min(rect.bottom, viewportHeight) - Math.max(rect.top, 0)
        );
        return { video, visibleArea: visibleWidth * visibleHeight };
      })
      .filter(({ video, visibleArea }) => visibleArea > 0 && video.readyState >= 1)
      .sort((left, right) => right.visibleArea - left.visibleArea)[0]?.video;
  }

  function waitForSeek(video, targetTime) {
    if (!video.seeking && Math.abs(video.currentTime - targetTime) < 0.15) {
      return Promise.resolve();
    }

    return new Promise((resolve) => {
      const timeout = window.setTimeout(resolve, 1500);
      video.addEventListener(
        "seeked",
        () => {
          window.clearTimeout(timeout);
          resolve();
        },
        { once: true }
      );
    });
  }

  function createAudioSampleSegments(durationSeconds) {
    if (durationSeconds <= 3) {
      return [
        {
          label: "完整",
          startSeconds: 0,
          durationSeconds: Math.max(1, durationSeconds)
        }
      ];
    }

    return [
      { label: "开头", startSeconds: 0, durationSeconds: 3 },
      {
        label: "中间",
        startSeconds: Math.max(0, durationSeconds / 2 - 1.5),
        durationSeconds: 3
      },
      {
        label: "结尾",
        startSeconds: Math.max(0, durationSeconds - 3),
        durationSeconds: 3
      }
    ];
  }

  async function prepareAudioCapture(expectedVideoId) {
    const currentVideo = getVideoInfo();

    if (!currentVideo.isYouTubeVideo || currentVideo.videoId !== expectedVideoId) {
      throw new Error("视频已切换，请重新解析当前视频。");
    }

    const video = getVisibleVideoElement();

    if (!video) {
      throw new Error("未找到当前视频播放器，请先播放视频后重试。");
    }

    if (!Number.isFinite(video.duration) || video.duration <= 0) {
      throw new Error("暂不支持直播或无法确定时长的视频。");
    }

    const segments = createAudioSampleSegments(video.duration);

    audioCapturePlaybackState = {
      video,
      videoId: expectedVideoId,
      currentTime: video.currentTime,
      paused: video.paused,
      muted: video.muted,
      volume: video.volume,
      playbackRate: video.playbackRate
    };

    video.pause();
    video.currentTime = segments[0].startSeconds;
    video.muted = false;
    video.volume = Math.max(video.volume, 0.5);
    video.playbackRate = 1;
    await waitForSeek(video, segments[0].startSeconds);

    return {
      ok: true,
      sourceDurationSeconds: video.duration,
      sampleDurationSeconds: segments.reduce(
        (total, segment) => total + segment.durationSeconds,
        0
      ),
      segments
    };
  }

  async function playAudioCaptureSegment(expectedVideoId, segment) {
    if (!audioCapturePlaybackState || audioCapturePlaybackState.videoId !== expectedVideoId) {
      throw new Error("音频捕获准备状态已失效，请重新开始。");
    }

    const startSeconds = Number(segment?.startSeconds);
    const durationSeconds = Number(segment?.durationSeconds);

    if (
      !Number.isFinite(startSeconds) ||
      startSeconds < 0 ||
      !Number.isFinite(durationSeconds) ||
      durationSeconds <= 0 ||
      durationSeconds > 3
    ) {
      throw new Error("音频采样时间无效。");
    }

    const video = audioCapturePlaybackState.video;
    video.pause();
    video.currentTime = Math.min(startSeconds, Math.max(0, video.duration - 0.1));
    await waitForSeek(video, video.currentTime);
    await video.play();
    await new Promise((resolve) => {
      const finish = () => {
        window.clearTimeout(timeout);
        video.removeEventListener("ended", finish);
        resolve();
      };
      const timeout = window.setTimeout(finish, durationSeconds * 1000);
      video.addEventListener("ended", finish, { once: true });
    });
    video.pause();
    return { ok: true };
  }

  async function restoreAudioCapturePlayback(expectedVideoId) {
    const state = audioCapturePlaybackState;

    if (!state || state.videoId !== expectedVideoId) {
      return { ok: true };
    }

    audioCapturePlaybackState = null;
    state.video.pause();
    state.video.currentTime = Math.min(state.currentTime, state.video.duration || state.currentTime);
    state.video.muted = state.muted;
    state.video.volume = state.volume;
    state.video.playbackRate = state.playbackRate;

    if (!state.paused) {
      await state.video.play().catch(() => {});
    }

    return { ok: true };
  }

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type === "GET_VIDEO_INFO") {
      sendResponse(getVideoInfo());
      return false;
    }

    if (message?.type === "GET_TRANSCRIPT") {
      const diagnostics = {
        extensionVersion: chrome.runtime.getManifest().version,
        videoId: message.videoId,
        pageType: window.location.pathname.startsWith("/shorts/") ? "shorts" : "watch",
        steps: []
      };

      getTranscript(message.videoId, diagnostics)
        .then(sendResponse)
        .catch((error) => {
          console.warn("[MochiLens] Transcript diagnostics", diagnostics);
          sendResponse({ ok: false, error: error.message, debug: diagnostics });
        });
      return true;
    }

    if (message?.type === "PREPARE_AUDIO_CAPTURE") {
      prepareAudioCapture(message.videoId)
        .then(sendResponse)
        .catch((error) => sendResponse({ ok: false, error: error.message }));
      return true;
    }

    if (message?.type === "PLAY_AUDIO_CAPTURE_SEGMENT") {
      playAudioCaptureSegment(message.videoId, message.segment)
        .then(sendResponse)
        .catch((error) => sendResponse({ ok: false, error: error.message }));
      return true;
    }

    if (message?.type === "RESTORE_AUDIO_CAPTURE_PLAYBACK") {
      restoreAudioCapturePlayback(message.videoId)
        .then(sendResponse)
        .catch((error) => sendResponse({ ok: false, error: error.message }));
      return true;
    }

    return false;
  });

  function notifyVideoInfoUpdated() {
    chrome.runtime.sendMessage(
      { type: "VIDEO_INFO_UPDATED", video: getVideoInfo() },
      () => {
        void chrome.runtime.lastError;
      }
    );
  }

  function handleSpaNavigation() {
    notifyVideoInfoUpdated();
    window.setTimeout(notifyVideoInfoUpdated, 500);
  }

  document.addEventListener("yt-navigate-finish", handleSpaNavigation);
  window.addEventListener("popstate", handleSpaNavigation);

  console.info("[MochiLens] Content script loaded.");
})();
